portfolio:
  name: "benchmark"

# [CURRENCIES]
currencies:
  - currency: USD
    ticker: CAD=X
  - currency: EUR
    ticker: EURCAD=X

# [TRANSACTIONS]
transactions:
  
- type: Buy
  date: 2022-05-05
  ticker: XIU.TO
  price: 28.92279434
  quantity: 1054.30674
  currency: CAD
  sector: ETF Equity
  geography: CAN
  asset_class: ETF Equity

- type: Buy
  date: 2022-05-05
  ticker: SPY
  price: 397.25787354
  quantity: 60.26439139
  currency: USD
  sector: ETF Equity
  geography: US
  asset_class: ETF Equity

- type: Buy
  date: 2022-05-05
  ticker: AGG
  price: 92.74882507
  quantity: 172.0812466
  currency: USD
  sector: ETF Fixed Income
  geography: US
  asset_class: ETF Fixed Income

- type: Buy
  date: 2022-05-05
  ticker: XBB.TO
  price: 25.58189964
  quantity: 794.663288
  currency: CAD
  sector: ETF Fixed Income
  geography: CAN
  asset_class: ETF Fixed Income