portfolio:
  name: "core"

# [FUNDS]
funds:
  - name: Fixed Income
    thesis: We generate alpha primarily through strategic duration positioning, while also capitalizing on short-term macro opportunities in commodities.
  - name: Industrials Fund
    thesis: We invest in high-quality industrial companies with strong competitive advantages, stable cash flows, and attractive valuations. Our strategy focuses on businesses benefiting from strong economic MOATS and long-term trends aiming to drive value creation for the fund.
  - name: Resources Fund
    thesis: We seek to invest in high-quality resource companies with strong fundamentals that are trading at a discount to intrinsic value. Our focus is on long-term value creation through disciplined capital allocation in undervalued sectors of the natural resources sector.
  - name: C&H Fund
    thesis: We primarily invest in high-quality Consumer and Healthcare companies with durable growth and strong fundamentals, aiming to generate consistent alpha through diversified, research-driven stock selection.
  - name: TMT Fund
    thesis: We aim to invest in businesses with strong competitive advantages in their niche and established market leadership. Companies we select display high growth potential and benefit from long-term industry trends that will continue to drive value.
  - name: Financials Fund
    thesis: We are a very good fund, make lots of money, and are very good at it.

# Dates are in YYYY-MM-DD format and are settlement dates
# [SECURITIES]
securities:
  # NSR removed since null in yfinance
  
  # Fixed Income
- ticker: XBB.TO
  fund: Fixed Income
  sector: Fixed Income
  geography: CAN
- ticker: AGG
  fund: Fixed Income
  sector: Fixed Income
  geography: US
- ticker: SPY
  fund: Fixed Income
  sector: Equity
  geography: US
- ticker: SPSB
  fund: Fixed Income
  sector: Fixed Income
  geography: US
- ticker: SCHP
  fund: Fixed Income
  sector: Fixed Income
  geography: US
- ticker: TLT
  fund: Fixed Income
  sector: Fixed Income
  geography: US

# Industrials Fund
- ticker: ACO-X.TO
  fund: Industrials Fund
  sector: Industrials
  geography: CAN
- ticker: GSL
  fund: Industrials Fund
  sector: Industrials
  geography: US
- ticker: TEX
  fund: Industrials Fund
  sector: Industrials
  geography: US
- ticker: CEG
  fund: Industrials Fund
  sector: Utilities
  geography: US
- ticker: WSC
  fund: Industrials Fund
  sector: Industrials
  geography: US

# Resources Fund
- ticker: WFG.TO
  fund: Resources Fund
  sector: Materials
  geography: CAN
- ticker: HBM.TO
  fund: Resources Fund
  sector: Materials
  geography: CAN
- ticker: MP
  fund: Resources Fund
  sector: Materials
  geography: US
- ticker: DOLE
  fund: Resources Fund
  sector: Consumer Staples
  geography: US

# C&H Fund
- ticker: CSH-UN.TO
  fund: C&H Fund
  sector: Real Estate
  geography: CAN
- ticker: L.TO
  fund: C&H Fund
  sector: Consumer Discretionary
  geography: CAN
- ticker: ISRG
  fund: C&H Fund
  sector: Healthcare
  geography: US
- ticker: MA
  fund: C&H Fund
  sector: Financials
  geography: US
- ticker: BLBD
  fund: C&H Fund
  sector: Consumer Discretionary
  geography: US

# Financials Fund
- ticker: CG
  fund: Financials Fund
  sector: Financials
  geography: US
- ticker: APO
  fund: Financials Fund
  sector: Financials
  geography: US
- ticker: AER
  fund: Financials Fund
  sector: Financials
  geography: US
- ticker: MA
  fund: Financials Fund
  sector: Financials
  geography: US
- ticker: AMSF
  fund: Financials Fund
  sector: Financials
  geography: US

- ticker: FFH.TO
  fund: Financials Fund
  sector: Financials
  geography: CAN

- ticker: RY.TO
  fund: Financials Fund
  sector: Financials
  geography: CAN

# TMT Fund
- ticker: AAPL
  fund: TMT Fund
  sector: Technology
  geography: US
- ticker: EA
  fund: TMT Fund
  sector: Technology
  geography: US
- ticker: AMAT
  fund: TMT Fund
  sector: Technology
  geography: US
- ticker: VEEV
  fund: TMT Fund
  sector: Healthcare
  geography: US
- ticker: TMUS
  fund: TMT Fund
  sector: Communication Services
  geography: US

- ticker: GOOG
  fund: TMT Fund
  sector: Communication Services
  geography: US

  # No longer in portfolio
- ticker: RSP
  fund: Fixed Income
  sector: Equity
  geography: US
- ticker: XIU.TO
  fund: Fixed Income
  sector: Equity
  geography: CAN

# [CURRENCIES]
currencies:
  - currency: USD
    ticker: CAD=X
  # - currency: EUR
  #   ticker: EURCAD=X

# [TRANSACTIONS]
transactions:
  - type: Buy
    date: 2022-05-05
    ticker: EA
    price: 121.57
    quantity: 16
    currency: USD

  - type: Buy
    date: 2022-05-05
    ticker: ISRG
    price: 238.04
    quantity: 8
    currency: USD

  - type: Buy
    date: 2022-05-05
    ticker: MA
    price: 358.41
    quantity: 5
    currency: USD

  - type: Buy
    date: 2022-05-05
    ticker: TEX
    price: 34.66
    quantity: 56
    currency: USD

  - type: Buy
    date: 2023-04-27
    ticker: AGG
    price: 97.83
    quantity: 155
    currency: USD

  - type: Buy
    date: 2023-04-27
    ticker: HBM.TO
    price: 6.68
    quantity: 225
    currency: CAD

  - type: Buy
    date: 2023-04-27
    ticker: XIU.TO
    price: 31.26
    quantity: 630
    currency: CAD

  - type: Buy
    date: 2023-04-27
    ticker: XBB.TO
    price: 28.15
    quantity: 741
    currency: CAD

  - type: Buy
    date: 2023-04-27
    ticker: L.TO
    price: 126.00
    quantity: 20
    currency: CAD

  - type: Buy
    date: 2023-04-27
    ticker: SPY
    price: 406.81
    quantity: 35
    currency: USD

  - type: Buy
    date: 2023-04-27
    ticker: APO
    price: 62.36
    quantity: 30
    currency: USD

  - type: Buy
    date: 2023-04-27
    ticker: AAPL
    price: 165.39
    quantity: 4
    currency: USD

  - type: Buy
    date: 2023-04-27
    ticker: CEG
    price: 76.42
    quantity: 25
    currency: USD

  - type: Buy
    date: 2023-12-27
    ticker: AMSF
    price: 47.20
    quantity: 45
    currency: USD

  - type: Buy
    date: 2023-12-27
    ticker: VEEV
    price: 189.04
    quantity: 5
    currency: USD

  - type: Sell
    date: 2023-12-27
    ticker: SPY
    price: 475.16
    quantity: 10
    currency: USD

  - type: Buy
    date: 2023-12-27
    ticker: GSL
    price: 20.29
    quantity: 101
    currency: USD

  - type: Sell
    date: 2023-12-27
    ticker: AGG
    price: 98.97
    quantity: 59
    currency: USD

  - type: Buy
    date: 2023-12-27
    ticker: SPSB
    price: 29.73
    quantity: 320
    currency: USD

  - type: Buy
    date: 2023-12-28
    ticker: WFG.TO
    price: 112.40
    quantity: 23
    currency: CAD

  - type: Sell
    date: 2023-12-28
    ticker: XIU.TO
    price: 31.90
    quantity: 111
    currency: CAD

  - type: Buy
    date: 2023-12-28
    ticker: CSH-UN.TO
    price: 11.60
    quantity: 107
    currency: CAD

  - type: Sell
    date: 2024-12-23
    ticker: XBB.TO
    price: 28.36
    quantity: 557
    currency: CAD

  - type: Sell
    date: 2024-12-23
    ticker: XIU.TO
    price: 37.43
    quantity: 519
    currency: CAD

  - type: Buy
    date: 2024-12-23
    ticker: ACO-X.TO
    price: 47.22
    quantity: 122
    currency: CAD

  - type: Buy
    date: 2024-12-23
    ticker: CG
    price: 50.37
    quantity: 51
    currency: USD

  - type: Buy
    date: 2024-12-23
    ticker: WSC
    price: 33.59
    quantity: 60
    currency: USD

  - type: Buy
    date: 2024-12-23
    ticker: AER
    price: 95.05
    quantity: 21
    currency: USD

  - type: Buy
    date: 2024-12-23
    ticker: BLBD
    price: 39.58
    quantity: 61
    currency: USD

  - type: Buy
    date: 2024-12-23
    ticker: TMUS
    price: 220.52
    quantity: 4
    currency: USD

  - type: Buy
    date: 2024-12-23
    ticker: MP
    price: 15.87
    quantity: 245
    currency: USD

  - type: Buy
    date: 2024-12-23
    ticker: DOLE
    price: 13.81
    quantity: 108
    currency: USD

  - type: Buy
    date: 2024-12-23
    ticker: AMAT
    price: 164.05
    quantity: 19
    currency: USD

  - type: Sell
    date: 2025-03-25
    ticker: AGG
    price: 98.46
    quantity: 96
    currency: USD

  - type: Sell
    date: 2025-03-25
    ticker: SPY
    price: 574.1601
    quantity: 25
    currency: USD

  - type: Sell
    date: 2025-03-25
    ticker: SPSB
    price: 30.0402
    quantity: 320
    currency: USD

  - type: Buy
    date: 2025-03-25
    ticker: TLT
    price: 89.8399
    quantity: 225
    currency: USD

  - type: Buy
    date: 2025-03-25
    ticker: SCHP
    price: 26.6199
    quantity: 256
    currency: USD

  - type: Sell
    date: 2025-06-16
    ticker: AAPL
    price: 196.2
    quantity: 4
    currency: USD

  - type: Sell
    date: 2025-06-16
    ticker: BLBD
    price: 41.022
    quantity: 61
    currency: USD

  - type: Sell
    date: 2025-06-16
    ticker: HBM.TO
    price: 13.07
    quantity: 225
    currency: CAD

  - type: Sell
    date: 2025-06-16
    ticker: DOLE
    price: 14.12
    quantity: 108
    currency: USD

  - type: Buy
    date: 2025-06-17
    ticker: GOOG
    price: 177.18
    quantity: 29
    currency: USD

  - type: Buy
    date: 2025-06-17
    ticker: FFH.TO
    price: 2415
    quantity: 2
    currency: CAD

  - type: Sell
    date: 2025-07-14
    ticker: MP
    price: 47.05
    quantity: 245
    currency: USD

  - type: Sell
    date: 2025-07-14
    ticker: MA
    price: 555.31
    quantity: 5
    currency: USD

  - type: Sell
    date: 2025-07-14
    ticker: CG
    price: 58.06
    quantity: 51
    currency: USD

  - type: Sell
    date: 2025-07-14
    ticker: EA
    price: 149.47
    quantity: 16
    currency: USD

  - type: Buy
    date: 2025-07-14
    ticker: RY.TO
    price: 180.31
    quantity: 33
    currency: CAD

  - type: Sell
    date: 2025-09-09
    ticker: TLT
    price: 89.11
    quantity: 225
    currency: USD
  
  # Conversion rate must be rate for 'from' currency to 'to' currency
  # Currently only USD<->CAD is supported
  # Conversions must be made on valid trading dates
  - type: Conversion
    date: 2025-10-14
    amount: 2166.75
    currency_from: USD
    currency_to: CAD
    conversion_rate: 1.3821

  - type: Buy
    date: 2025-10-15
    ticker: IAU
    price: 77.7999
    quantity: 70
    currency: USD

  - type: Buy
    date: 2025-10-15
    ticker: LUNR
    price: 12.48
    quantity: 160
    currency: USD
  
  - type: Buy
    date: 2025-10-15
    ticker: CGY.TO
    price: 52.89
    quantity: 60
    currency: CAD