portfolio:
  name: "core"

transactions:
  - type: Buy
    date: 2022-05-05
    ticker: EA
    price: 121.57
    quantity: 16
    currency: USD
    sector: Technology, Media, Telecom
    geography: US
    asset_class: Equity

  - type: Buy
    date: 2022-05-05
    ticker: ISRG
    price: 238.04
    quantity: 8
    currency: USD
    sector: Consumer and Healthcare
    geography: US
    asset_class: Equity

  - type: Buy
    date: 2022-05-05
    ticker: MA
    price: 358.41
    quantity: 5
    currency: USD
    sector: Financials
    geography: US
    asset_class: Equity

  - type: Buy
    date: 2022-05-05
    ticker: TEX
    price: 34.66
    quantity: 56
    currency: USD
    sector: Industrials
    geography: US
    asset_class: Equity

  - type: Buy
    date: 2023-04-27
    ticker: AGG
    price: 97.83
    quantity: 155
    currency: USD
    sector: ETF Fixed Income
    geography: US
    asset_class: ETF Fixed Income

  - type: Buy
    date: 2023-04-27
    ticker: HBM.TO
    price: 6.68
    quantity: 225
    currency: CAD
    sector: Materials
    geography: CAN
    asset_class: Equity

  - type: Buy
    date: 2023-04-27
    ticker: XIU.TO
    price: 31.26
    quantity: 630
    currency: CAD
    sector: ETF Equity
    geography: CAN
    asset_class: ETF Equity

  - type: Buy
    date: 2023-04-27
    ticker: XBB.TO
    price: 28.15
    quantity: 741
    currency: CAD
    sector: ETF Fixed Income
    geography: CAN
    asset_class: ETF Fixed Income

  - type: Buy
    date: 2023-04-27
    ticker: L.TO
    price: 126.00
    quantity: 20
    currency: CAD
    sector: Consumer and Healthcare
    geography: CAN
    asset_class: Equity

  - type: Buy
    date: 2023-04-27
    ticker: SPY
    price: 406.81
    quantity: 35
    currency: USD
    sector: ETF Equity
    geography: US
    asset_class: ETF Equity

  - type: Buy
    date: 2023-04-27
    ticker: APO
    price: 62.36
    quantity: 30
    currency: USD
    sector: Financials
    geography: US
    asset_class: Equity

  - type: Buy
    date: 2023-04-27
    ticker: AAPL
    price: 165.39
    quantity: 4
    currency: USD
    sector: Technology, Media, Telecom
    geography: US
    asset_class: Equity

  - type: Buy
    date: 2023-04-27
    ticker: CEG
    price: 76.42
    quantity: 25
    currency: USD
    sector: Industrials
    geography: US
    asset_class: Equity

  - type: Buy
    date: 2023-12-27
    ticker: AMSF
    price: 47.20
    quantity: 45
    currency: USD
    sector: Financials
    geography: US
    asset_class: Equity

  - type: Buy
    date: 2023-12-27
    ticker: VEEV
    price: 189.04
    quantity: 5
    currency: USD
    sector: Technology, Media, Telecom
    geography: US
    asset_class: Equity

  - type: Sell
    date: 2023-12-27
    ticker: SPY
    price: 475.16
    quantity: 10
    currency: USD
    sector: ETF Equity
    geography: US
    asset_class: ETF Equity

  - type: Buy
    date: 2023-12-27
    ticker: GSL
    price: 20.29
    quantity: 101
    currency: USD
    sector: Industrials
    geography: US
    asset_class: Equity

  - type: Sell
    date: 2023-12-27
    ticker: AGG
    price: 98.97
    quantity: 59
    currency: USD
    sector: ETF Fixed Income
    geography: US
    asset_class: ETF Fixed Income

  - type: Buy
    date: 2023-12-27
    ticker: SPSB
    price: 29.73
    quantity: 320
    currency: USD
    sector: ETF Fixed Income
    geography: US
    asset_class: ETF Fixed Income

  - type: Buy
    date: 2023-12-28
    ticker: WFG.TO
    price: 112.40
    quantity: 23
    currency: CAD
    sector: Natural Resources
    geography: CAN
    asset_class: Equity

  - type: Sell
    date: 2023-12-28
    ticker: XIU.TO
    price: 31.90
    quantity: 111
    currency: CAD
    sector: ETF Equity
    geography: CAN
    asset_class: ETF Equity

  - type: Buy
    date: 2023-12-28
    ticker: CSH-UN.TO
    price: 11.60
    quantity: 107
    currency: CAD
    sector: Consumer and Healthcare
    geography: CAN
    asset_class: Equity

  - type: Sell
    date: 2024-12-23
    ticker: XBB.TO
    price: 28.36
    quantity: 557
    currency: CAD
    sector: ETF Fixed Income
    geography: CAN
    asset_class: ETF Fixed Income

  - type: Sell
    date: 2024-12-23
    ticker: XIU.TO
    price: 37.43
    quantity: 519
    currency: CAD
    sector: ETF Equity
    geography: CAN
    asset_class: ETFEquity

  - type: Buy
    date: 2024-12-23
    ticker: ACO-X.TO
    price: 47.22
    quantity: 122
    currency: CAD
    sector: Industrials
    geography: CAN
    asset_class: Equity

  - type: Buy
    date: 2024-12-23
    ticker: CG
    price: 50.37
    quantity: 51
    currency: USD
    sector: Financials
    geography: US
    asset_class: Equity

  - type: Buy
    date: 2024-12-23
    ticker: WSC
    price: 33.59
    quantity: 60
    currency: USD
    sector: Industrials
    geography: US
    asset_class: Equity

  - type: Buy
    date: 2024-12-23
    ticker: AER
    price: 95.05
    quantity: 21
    currency: USD
    sector: Financials
    geography: US
    asset_class: Equity

  - type: Buy
    date: 2024-12-23
    ticker: BLBD
    price: 39.58
    quantity: 61
    currency: USD
    sector: Consumer and Healthcare
    geography: US
    asset_class: Equity

  - type: Buy
    date: 2024-12-23
    ticker: TMUS
    price: 220.52
    quantity: 4
    currency: USD
    sector: Technology, Media, Telecom
    geography: US
    asset_class: Equity

  - type: Buy
    date: 2024-12-23
    ticker: MP
    price: 15.87
    quantity: 245
    currency: USD
    sector: Natural Resources
    geography: US
    asset_class: Equity

  - type: Buy
    date: 2024-12-23
    ticker: DOLE
    price: 13.81
    quantity: 108
    currency: USD
    sector: Consumer and Healthcare
    geography: US
    asset_class: Equity

  - type: Buy
    date: 2024-12-23
    ticker: AMAT
    price: 164.05
    quantity: 19
    currency: USD
    sector: Technology, Media, Telecom
    geography: US
    asset_class: Equity

  - type: Sell
    date: 2025-03-25
    ticker: AGG
    price: 98.46
    quantity: 96
    currency: USD
    sector: ETF Fixed Income
    geography: US
    asset_class: ETF Fixed Income

  - type: Sell
    date: 2025-03-25
    ticker: SPY
    price: 574.1601
    quantity: 25
    currency: USD
    sector: ETF Equity
    geography: US
    asset_class: Equity

  - type: Sell
    date: 2025-03-25
    ticker: SPSB
    price: 30.0402
    quantity: 320
    currency: USD
    sector: ETF Fixed Income
    geography: US
    asset_class: ETF Fixed Income

  - type: Buy
    date: 2025-03-25
    ticker: TLT
    price: 89.8399
    quantity: 225
    currency: USD
    sector: ETF Fixed Income
    geography: US
    asset_class: ETF Fixed Income

  - type: Buy
    date: 2025-03-25
    ticker: SCHP
    price: 26.6199
    quantity: 256
    currency: USD
    sector: ETF Fixed Income
    geography: US
    asset_class: ETF Fixed Income

  - type: Sell
    date: 2025-06-16
    ticker: AAPL
    price: 196.2
    quantity: 4
    currency: USD
    sector: Technology, Media, Telecom
    geography: US
    asset_class: Equity

  - type: Sell
    date: 2025-06-16
    ticker: BLBD
    price: 41.022
    quantity: 61
    currency: USD
    sector: Consumer and Healthcare
    geography: US
    asset_class: Equity

  - type: Sell
    date: 2025-06-16
    ticker: HBM.TO
    price: 13.07
    quantity: 225
    currency: CAD
    sector: Natural Resources
    geography: CAN
    asset_class: Equity

  - type: Sell
    date: 2025-06-16
    ticker: DOLE
    price: 14.12
    quantity: 108
    currency: USD
    sector: Consumer and Healthcare
    geography: US
    asset_class: Equity

  - type: Buy
    date: 2025-06-17
    ticker: GOOG
    price: 177.18
    quantity: 29
    currency: USD
    sector: Technology, Media, Telecom
    geography: US
    asset_class: Equity

  - type: Buy
    date: 2025-06-17
    ticker: FFH.TO
    price: 2415
    quantity: 2
    currency: CAD
    sector: Financials
    geography: CAN
    asset_class: Equity

  - type: Sell
    date: 2025-07-14
    ticker: MP
    price: 47.05
    quantity: 245
    currency: USD
    sector: Natural Resources
    geography: US
    asset_class: Equity

  - type: Sell
    date: 2025-07-14
    ticker: MA
    price: 555.31
    quantity: 5
    currency: USD
    sector: Financials
    geography: US
    asset_class: Equity

  - type: Sell
    date: 2025-07-14
    ticker: CG
    price: 58.06
    quantity: 51
    currency: USD
    sector: Financials
    geography: US
    asset_class: Equity

  - type: Sell
    date: 2025-07-14
    ticker: EA
    price: 149.47
    quantity: 16
    currency: USD
    sector: Technology, Media, Telecom
    geography: US
    asset_class: Equity

  - type: Buy
    date: 2025-07-14
    ticker: RY.TO
    price: 180.31
    quantity: 33
    currency: CAD
    sector: Financials
    geography: CAN
    asset_class: Equity

  - type: Sell
    date: 2025-09-09
    ticker: TLT
    price: 89.11
    quantity: 225
    currency: USD
    sector: ETF Fixed Income
    geography: US
    asset_class: ETF Fixed Income

  # Conversion rate must be rate for 'from' currency to 'to' currency
  # Currently only USD<->CAD is supported
  # Conversions must be made on valid trading dates
  - type: Conversion
    date: 2025-10-14
    amount: 2166.75
    currency_from: USD
    currency_to: CAD
    conversion_rate: 1.3821

  - type: Buy
    date: 2025-10-15
    ticker: IAU
    price: 77.7999
    quantity: 70
    currency: USD
    sector: Absolute Return
    geography: US
    asset_class: Gold

  - type: Buy
    date: 2025-10-15
    ticker: LUNR
    price: 12.48
    quantity: 160
    currency: USD
    sector: Absolute Return
    geography: US
    asset_class: Equity

  - type: Buy
    date: 2025-10-15
    ticker: CGY.TO
    price: 52.89
    quantity: 60
    currency: CAD
    sector: Industrials
    geography: CAN
    asset_class: Equity

  - type: Buy
    date: 2025-11-25
    ticker: BIL
    price: 91.6699
    quantity: 310
    currency: USD
    sector: ETF Fixed Income
    geography: US
    asset_class: ETF Fixed Income