name: Ping DFIC Fund Monitor Site

on:
  schedule:
    - cron: '*/5 * * * *' # Here it runs every 5 mins
  workflow_dispatch:

jobs:
  keepalive:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Streamlit app
        run: curl -s https://dfic-fund.streamlit.app/ || echo "Ping failed"
